/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-24 17:48:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1624549179620L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_WebServer/coja/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>메인 페이지</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* border 주석 풀면 전체적인 div 구획 확인 가능 */\r\n");
      out.write("div {\r\n");
      out.write("	/* border: 1px solid black; */\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header 시작 */\r\n");
      out.write(".header-container {\r\n");
      out.write("	padding-top: 1%;\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 64px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 로고박스 */\r\n");
      out.write(".header-logobox {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 로고 */\r\n");
      out.write("#header-logo {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 검색창박스 */\r\n");
      out.write(".header-searchbox {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 검색입력창 */\r\n");
      out.write(".header-search-area {\r\n");
      out.write("	border: 2px solid #c7f1ec;\r\n");
      out.write("	width: 75%;\r\n");
      out.write("	height: 38px;\r\n");
      out.write("	line-height: 38px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	margin-right: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼 */\r\n");
      out.write(".header-search-button {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	width: 7%;\r\n");
      out.write("	height: 38px;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	margin-left: 0;\r\n");
      out.write("	margin-bottom: 6px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼박스 */\r\n");
      out.write(".header-buttonbox {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 내블로그,마이페이지,로그아웃 */\r\n");
      out.write(".header-button {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	height: 38px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin-right: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bt-1, #bt-2, #bt-3 {\r\n");
      out.write("	background-color: gainsboro;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  로그인 시작 */\r\n");
      out.write("#loginFormModal {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn-area {\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#savecheck {\r\n");
      out.write("	width: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login {\r\n");
      out.write("	width: 375px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#findId {\r\n");
      out.write("	width: 115px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#findPw {\r\n");
      out.write("	width: 130px;\r\n");
      out.write("	margin: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#joinMember {\r\n");
      out.write("	width: 90px;\r\n");
      out.write("	margin-left: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  로그인 끝 */\r\n");
      out.write("\r\n");
      out.write("/* header 끝 */\r\n");
      out.write("\r\n");
      out.write("/* ------------------------------영역구분선------------------------------ */\r\n");
      out.write("\r\n");
      out.write("/* content 시작 */\r\n");
      out.write("#content {\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigator {\r\n");
      out.write("	height: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메뉴박스 */\r\n");
      out.write("#navi {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 인기글 네비관련 */\r\n");
      out.write("#navi>li {\r\n");
      out.write("	width: 11%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	float: left;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 80px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 인기글 네비관련 */\r\n");
      out.write("#navi li a:hover {\r\n");
      out.write("	color: #c7f1ec;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 인기글 네비관련 */\r\n");
      out.write("#navi li a {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-family: \"굴림\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 전체 인기글 카드를 감싸는 div 영역 */\r\n");
      out.write("/* background-color 주석 풀면 해당 영역 확인 가능 */\r\n");
      out.write("#cardArea {\r\n");
      out.write("	height: 410px;\r\n");
      out.write("	/* background-color: red; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 각각의 인기글 카드 위치잡는 css */\r\n");
      out.write(".card {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-left: 8px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 전체 최신글을 감싸는 영역 */\r\n");
      out.write("/* background-color 주석 풀면 해당 영역 확인 가능 */\r\n");
      out.write("#newestArea {\r\n");
      out.write("	height: 1080px;\r\n");
      out.write("	/* background-color: red; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \"최신글\"이라고 써져있는 span 태그를 감싸는 div 영역 */\r\n");
      out.write("/* background-color 주석 풀면 해당 영역 확인 가능 */\r\n");
      out.write("#newestText {\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	/* background-color: red; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \"최신글\" 이라고 써져있는 span 태그 부분 */\r\n");
      out.write("#newestText>span {\r\n");
      out.write("	margin-left: 25px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	line-height: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 각각의 최신글을 감싸는 영역 */\r\n");
      out.write("/* background-color 주석 풀면 해당 영역 확인 가능 */\r\n");
      out.write("#newestArea>.newestContent {\r\n");
      out.write("	width: 1160px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	/* background-color: red; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 1~3번 최신글의 이미지 영역 */\r\n");
      out.write("#imageBox1, #imageBox2, #imageBox3 {\r\n");
      out.write("	width: 250px;\r\n");
      out.write("	height: 250px;\r\n");
      out.write("	margin-top: 25px;\r\n");
      out.write("	margin-left: 25px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 1~3번 최신글의 텍스트 영역 */\r\n");
      out.write("#contentBox1, #contentBox2, #contentBox3 {\r\n");
      out.write("	height: 250px;\r\n");
      out.write("	width: 820px;\r\n");
      out.write("	margin-top: 25px;\r\n");
      out.write("	margin-left: 25px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	background-color: tomato;\r\n");
      out.write("}\r\n");
      out.write("/* content 끝 */\r\n");
      out.write("\r\n");
      out.write("/* ------------------------------영역구분선------------------------------ */\r\n");
      out.write("\r\n");
      out.write("/* footer 시작 */\r\n");
      out.write(".footer {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	line-height: 60px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	background-color: #e9e9e9;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-text {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: gray;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin-right: 1.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* footer 끝 */\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<div class=\"header-container\">\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<!-- 로고 -->\r\n");
      out.write("			<div class=\"header-logobox\">\r\n");
      out.write("				<img src=\"https://assets.bigcartel.com/theme_images/10846261/cojalogo.png?auto=format&fit=max&h=500&w=1800\" id=\"header-logo\"></img>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 검색 -->\r\n");
      out.write("			<div class=\"header-searchbox\">\r\n");
      out.write("				<input type=\"search\" class=\"header-search-area\"\r\n");
      out.write("					id=\"search-text-area\" placeholder=\"  검색할 단어를 입력하세요.\">\r\n");
      out.write("				<button class=\"header-search-button\">\r\n");
      out.write("					<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\"\r\n");
      out.write("						fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                        <path\r\n");
      out.write("							d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\" />\r\n");
      out.write("                    </svg>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 버튼3 -->\r\n");
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ===============================영역구분선=============================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- content -->\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("		<!-- 캐러셀 -->\r\n");
      out.write("		<div id=\"carouselExampleIndicators\" class=\"carousel slide\"\r\n");
      out.write("			data-ride=\"carousel\">\r\n");
      out.write("			<ol class=\"carousel-indicators\">\r\n");
      out.write("				<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\"\r\n");
      out.write("					class=\"active\"></li>\r\n");
      out.write("				<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("				<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("			</ol>\r\n");
      out.write("			<div class=\"carousel-inner\">\r\n");
      out.write("				<div class=\"carousel-item active\">\r\n");
      out.write("					<img src=\"http://jpcamara.com/wp-content/uploads/2015/02/carousel.jpg\"\r\n");
      out.write("						class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"http://jpcamara.com/wp-content/uploads/2015/02/carousel.jpg\"\r\n");
      out.write("						class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"http://jpcamara.com/wp-content/uploads/2015/02/carousel.jpg\"\r\n");
      out.write("						class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("				role=\"button\" data-slide=\"prev\"> <span\r\n");
      out.write("				class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("				class=\"sr-only\">Previous</span>\r\n");
      out.write("			</a> <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\"\r\n");
      out.write("				role=\"button\" data-slide=\"next\"> <span\r\n");
      out.write("				class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("				class=\"sr-only\">Next</span>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 인기글 네비게이터 -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<div id=\"navigator\">\r\n");
      out.write("				<ul id=\"navi\">\r\n");
      out.write("					<li><a hrdf=\"#\">전체인기글</a></li>\r\n");
      out.write("					<li><a hrdf=\"#\">JAVA 인기글</a></li>\r\n");
      out.write("					<li><a hrdf=\"#\">JDBC 인기글</a></li>\r\n");
      out.write("					<li><a hrdf=\"#\">DB인기글</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 인기글 card -->\r\n");
      out.write("		<div id=cardArea>\r\n");
      out.write("			<!-- 인기글 1 -->\r\n");
      out.write("			<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("				<img src=\"https://www.bordbia.ie/globalassets/bordbia.ie/about/man-in-a-business-suit-on-a-laptop\" class=\"card-img-top\"\r\n");
      out.write("					alt=\"...\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">포스팅 제목</h5>\r\n");
      out.write("					<p class=\"card-text\">Some quick example text to build on the\r\n");
      out.write("						card title and make up the bulk of the card's content.</p>\r\n");
      out.write("					<a href=\"#\" class=\"btn btn-primary\">포스팅으로</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 인기글 2 -->\r\n");
      out.write("			<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("				<img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi-Pyk3TsTwrMUWXCWv26lVAM292ri47K7yA&usqp=CAU\" class=\"card-img-top\"\r\n");
      out.write("					alt=\"...\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">포스팅 제목</h5>\r\n");
      out.write("					<p class=\"card-text\">Some quick example text to build on the\r\n");
      out.write("						card title and make up the bulk of the card's content.</p>\r\n");
      out.write("					<a href=\"#\" class=\"btn btn-primary\">포스팅으로</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("				<img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS2Rcn9p4u9neUfgj6BRZUc82T6ahsblA6oMbCSgqMGwSdy9Kt6ZJFZdll8R0afwTZazE&usqp=CAU\" class=\"card-img-top\"\r\n");
      out.write("					alt=\"...\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">포스팅 제목</h5>\r\n");
      out.write("					<p class=\"card-text\">Some quick example text to build on the\r\n");
      out.write("						card title and make up the bulk of the card's content.</p>\r\n");
      out.write("					<a href=\"#\" class=\"btn btn-primary\">포스팅으로</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 인기글 3 -->\r\n");
      out.write("			<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("				<img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1E60PzPbXCpzaVsl-yeBtCFei-7A17sb2MRKojUzfhVyp1R-HxG6DBEtc165a71BeVEc&usqp=CAU\" class=\"card-img-top\"\r\n");
      out.write("					alt=\"...\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">포스팅 제목</h5>\r\n");
      out.write("					<p class=\"card-text\">Some quick example text to build on the\r\n");
      out.write("						card title and make up the bulk of the card's content.</p>\r\n");
      out.write("					<a href=\"#\" class=\"btn btn-primary\">포스팅으로</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 최신글 -->\r\n");
      out.write("		<div id=\"newestArea\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"newestText\">\r\n");
      out.write("				<span>최신글</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<!-- 최신글 1 -->\r\n");
      out.write("			<div class=\"newestContent\">\r\n");
      out.write("				<div id=\"imageBox1\">이미지 상자 1</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"contentBox1\">텍스트 상자 1</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 최신글 2 -->\r\n");
      out.write("			<div class=\"newestContent\">\r\n");
      out.write("				<div id=\"imageBox2\">이미지 상자 1</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"contentBox2\">텍스트 상자 1</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 최신글 3 -->\r\n");
      out.write("			<div class=\"newestContent\">\r\n");
      out.write("				<div id=\"imageBox3\">이미지 상자 1</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"contentBox3\">텍스트 상자 1</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ===============================영역구분선=============================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<a href=\"#\" class=\"footer-text\" id=\"ft-t1\">회사소개</a> <a href=\"#\"\r\n");
      out.write("			class=\"footer-text\" id=\"ft-t2\">운영정책</a> <a href=\"#\"\r\n");
      out.write("			class=\"footer-text\" id=\"ft-t3\">이용약관</a> <a href=\"#\"\r\n");
      out.write("			class=\"footer-text\" id=\"ft-t4\">고객센터</a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div class=\"modal fade\" id=\"loginForm\" data-backdrop=\"static\"\r\n");
      out.write("		data-keyboard=\"false\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" id=\"loginFormModal\">\r\n");
      out.write("			<div class=\"modal-content border-0\">\r\n");
      out.write("				<div class=\"modal-header border-0\">\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login\"\r\n");
      out.write("						onsubmit=\"return loginValidate();\">\r\n");
      out.write("						<table align=\"center\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th width=\"100px\" height=\"45px\"><label for=\"memId\">아이디</label></th>\r\n");
      out.write("								<td><input type=\"text\" size=\"26\" id=\"memId\" name=\"memId\"\r\n");
      out.write("									placeholder=\" 아이디를 입력해주세요.\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.saveId.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th width=\"100px\" height=\"45px\"><label for=\"memPw\">비밀번호</label></th>\r\n");
      out.write("								<td><input type=\"password\" size=\"26\" id=\"memPw\"\r\n");
      out.write("									name=\"memPw\" placeholder=\" 비밀번호를 입력해주세요.\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"checkbox mb-3\" id=\"savecheck\">\r\n");
      out.write("							<label> <input type=\"checkbox\" name=\"save\" id=\"save\"\r\n");
      out.write("								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> 아이디 저장\r\n");
      out.write("							</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<button class=\"btn btn-secondary\" id=\"login\" type=\"submit\">로그인</button>\r\n");
      out.write("						<div class=\"login-btn-area\">\r\n");
      out.write("							<a class=\"btn btn-secondary\" href=\"#\" role=\"button\" id=\"findId\">아이디\r\n");
      out.write("								찾기</a> <a class=\"btn btn-secondary\" href=\"#\" role=\"button\"\r\n");
      out.write("								id=\"findPw\">비밀번호 찾기</a> <a class=\"btn btn-secondary\"\r\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/signUp\" role=\"button\"\r\n");
      out.write("								id=\"joinMember\">회원가입</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			// 로그인 수행 시 아이디/비밀번호가 작성 되었는지 확인하는 유효성 검사\r\n");
      out.write("			function loginValidate() {\r\n");
      out.write("				// Validate : 유효한지 확인하다\r\n");
      out.write("\r\n");
      out.write("				// 아이디가 입력되지 않았을 경우\r\n");
      out.write("				// \"아이디를 입력해주세요\" 경고창을 띄우고\r\n");
      out.write("				// 로그인을 수행하지 않음\r\n");
      out.write("				if ($(\"#memberId\").val().trim().length == 0) {\r\n");
      out.write("					// $(\"#memberId\") : 아이디 속성값이 memberId인 input 태그 선택\r\n");
      out.write("					// .val() : input 태그에 작성된 값을 얻어옴\r\n");
      out.write("					// .trim() : 얻어온 값 양쪽에 작성된 공백문자를 제거\r\n");
      out.write("					// .length : 공백 제거 후 값의 길이\r\n");
      out.write("\r\n");
      out.write("					// sweetalert로 경고 출력\r\n");
      out.write("					swal({\r\n");
      out.write("						\"icon\" : \"warning\",\r\n");
      out.write("						\"title\" : \"아이디를 입력해주세요\"\r\n");
      out.write("					}).then(function() {\r\n");
      out.write("						// 아이디 입력창으로 포커스 이동\r\n");
      out.write("						$(\"#memberId\").focus();\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("					// 제출되지 않도록 submit 기본 이벤트 제거\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				// 비밀번호가 입력되지 않았을 경우\r\n");
      out.write("				// \"비밀번호를 입력해주세요\" 경고창을 띄우고\r\n");
      out.write("				// 로그인을 수행하지 않음\r\n");
      out.write("				if ($(\"#memberPw\").val().trim().length == 0) {\r\n");
      out.write("					// $(\"#memberPw\") : 아이디 속성값이 memberPw인 input 태그 선택\r\n");
      out.write("					// .val() : input 태그에 작성된 값을 얻어옴\r\n");
      out.write("					// .trim() : 얻어온 값 양쪽에 작성된 공백문자를 제거\r\n");
      out.write("					// .length : 공백 제거 후 값의 길이\r\n");
      out.write("\r\n");
      out.write("					// sweetalert로 경고 출력\r\n");
      out.write("					swal({\r\n");
      out.write("						\"icon\" : \"warning\",\r\n");
      out.write("						\"title\" : \"비밀번호를 입력해주세요\"\r\n");
      out.write("					}).then(function() {\r\n");
      out.write("						// 아이디 입력창으로 포커스 이동\r\n");
      out.write("						$(\"#memberPw\").focus();\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("					// 제출되지 않도록 submit 기본 이벤트 제거\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				//return false; // submit 기본 이벤트 제거\r\n");
      out.write("				// return true; 또는 아무것도 반환하지 않으면 submit 수행\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("			integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("			crossorigin=\"anonymous\"></script>\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("			integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\"\r\n");
      out.write("			crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/main.jsp(5,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      // /WEB-INF/views/main.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(5,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main.jsp(326,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginMember }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"header-buttonbox\">\r\n");
          out.write("						<button type=\"button\" class=\"header-button btn btn-secondary\"\r\n");
          out.write("							id=\"bt-1\">ID/PW찾기</button>\r\n");
          out.write("						<button type=\"button\" class=\"header-button btn btn-secondary\"\r\n");
          out.write("							id=\"bt-2\" data-toggle=\"modal\" data-target=\"#loginForm\">로그인</button>\r\n");
          out.write("						<button type=\"button\" class=\"header-button btn btn-secondary\"\r\n");
          out.write("							id=\"bt-3\">회원가입</button>\r\n");
          out.write("					</div>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"header-buttonbox\">\r\n");
          out.write("						<button type=\"button\" class=\"header-button btn btn-secondary\" id=\"bt-1\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myblog\">내 블로그</button>\r\n");
          out.write("						<button type=\"button\" class=\"header-button btn btn-secondary\" id=\"bt-2\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myPage\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</button>\r\n");
          out.write("						<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout\"><button type=\"button\" class=\"header-button btn btn-secondary\" id=\"bt-3\">로그아웃</button></a>\r\n");
          out.write("					</div>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/main.jsp(530,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty cookie.saveId.value }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/main.jsp(531,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ch");
      // /WEB-INF/views/main.jsp(531,7) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(531,7) 'checked'",_jsp_getExpressionFactory().createValueExpression("checked",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/main.jsp(550,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty title }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<script>\r\n");
          out.write("				swal({\r\n");
          out.write("					\"icon\" : \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\r\n");
          out.write("					\"title\" : \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\",\r\n");
          out.write("					\"text\" : \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("				});\r\n");
          out.write("			</script>\r\n");
          out.write("\r\n");
          out.write("			");
          out.write("\r\n");
          out.write("			");
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fremove_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fremove_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/main.jsp(561,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("icon");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f1 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f1_reused = false;
    try {
      _jspx_th_c_005fremove_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/main.jsp(562,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f1.setVar("title");
      int _jspx_eval_c_005fremove_005f1 = _jspx_th_c_005fremove_005f1.doStartTag();
      if (_jspx_th_c_005fremove_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f1);
      _jspx_th_c_005fremove_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f2 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f2_reused = false;
    try {
      _jspx_th_c_005fremove_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/main.jsp(563,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f2.setVar("text");
      int _jspx_eval_c_005fremove_005f2 = _jspx_th_c_005fremove_005f2.doStartTag();
      if (_jspx_th_c_005fremove_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f2);
      _jspx_th_c_005fremove_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f2_reused);
    }
    return false;
  }
}
